[package]
name = "docker-mdns"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bollard = "0.11"
chrono = "0.4"
dbus = "0.9"
futures-core = "0.3"
futures-util = "0.3"
if-addrs = "0.6"
log = "0.4"
pretty_env_logger = "0.4"

[dependencies.serde]
version = "1.0"
features = [
    "derive",
]

[dependencies.tokio]
version = "1.0"
features = [
    "macros",
    "rt-multi-thread",
]

#[target.armv7-unknown-linux-gnueabihf]
#linker = "arm-linux-gnueabihf-gcc"
