[package]
name = "docker-mdns"
version = "0.1.0"
edition = "2021"
rust-version = "1.60.0"
resolver = "2"

[dependencies]
anyhow = "1.0"
bollard = "0.13"
futures-core = "0.3"
futures-util = "0.3"
if-addrs = "0.7"
log = "0.4"
pretty_env_logger = "0.4"

[dependencies.serde]
version = "1.0"
features = [
    "derive",
]

[dependencies.tokio]
version = "1.21"
features = [
    "macros",
    "rt-multi-thread",
]

[dependencies.zbus]
version = "3.1"
default-features = false
features = [
    "tokio",
]
