[target.aarch64-unknown-linux-gnu]
image = "rustcross:dbus-aarch64"

[target.armv7-unknown-linux-gnueabihf]
image = "rustcross:dbus-armv7"

[target.x86_64-unknown-linux-gnu]
image = "rustcross:dbus-amd64"

[build.env]
passthrough = [
    "RUSTFLAGS",
]
