# vim:ft=dockerfile:
ARG DEBIAN_VERSION
ARG PLATFORM
FROM --platform=linux/${PLATFORM} debian:${DEBIAN_VERSION}

ARG TARGET
COPY target/${TARGET}/release/docker-mdns /usr/local/bin/

ENTRYPOINT ["docker-mdns"]
