# vim:ft=dockerfile:
ARG PLATFORM
FROM --platform=linux/${PLATFORM} debian:bullseye-20211011-slim

ARG ARCH
RUN dpkg --add-architecture ${ARCH} \
    && apt-get update \
    && apt-get install \
        --assume-yes \
        --no-install-recommends \
        libdbus-1-3:${ARCH}

ARG TARGET
COPY target/${TARGET}/release/docker-mdns /usr/local/bin/

ENTRYPOINT ["docker-mdns"]
