---
name: "Docker Push"

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  push:
    name: "Docker Push"
    runs-on: "ubuntu-latest"
    permissions:
      packages: "write"
      contents: "read"
    strategy:
      matrix:
        arch:
          - "amd64"
          - "armv7"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 1

      - name: "Target Cache"
        uses: "actions/cache@v1"
        env:
          cache-name: "target-cache"
        with:
          path: "target"
          key: "stable-${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}"

      - name: "Install Rust Toolchain"
        uses: "actions-rs/toolchain@v1"
        with:
          override: true
          profile: "minimal"
          toolchain: "stable"

      - name: "Install Cross"
        run: |
          cargo install cross

      - name: "Build"
        id: "build"
        env:
          IMAGE_NAME: "docker-mdns"
        run: |
          make image${{ matrix.arch }}

          echo "::set-output name=base_image_name::${IMAGE_NAME}"
          echo "::set-output name=image_name::${IMAGE_NAME}:${{ matrix.arch }}"

      - name: "Registry Login"
        run: |
          docker login ghcr.io \
            --username "${{ github.actor }}" \
            --password-stdin \
            <<< ${{ secrets.GITHUB_TOKEN }}

      - name: "Push Image"
        run: |
          BASE_IMAGE_NAME="${{ steps.build.outputs.base_image_name }}"
          IMAGE_NAME="${{ steps.build.outputs.image_name }}"
          IMAGE_ID="ghcr.io/${{ github.repository_owner }}/${BASE_IMAGE_NAME}"
          IMAGE_ID="$(echo ${IMAGE_ID} | tr '[A-Z]' '[a-z]')"
          VERSION="$(echo "${{ github.ref }}" | sed 's#.*/\(.*\)#\1#')"

          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            VERSION="$(echo "${VERSION}" | sed -e 's/^v//')"
          fi

          if [ "${VERSION}" == "main" ]; then
            VERSION="${{ matrix.arch }}-latest"
          fi

          echo IMAGE_ID="${IMAGE_ID}"
          echo VERSION="${VERSION}"

          # Tag
          echo "Tagging"
          docker tag "${IMAGE_NAME}" "${IMAGE_ID}:${{ matrix.arch }}"
          docker tag "${IMAGE_NAME}" "${IMAGE_ID}:${VERSION}"

          # Push
          echo "Pushing"
          docker push "${IMAGE_ID}:${{ matrix.arch }}"
          docker push "${IMAGE_ID}:${VERSION}"
